replicaCount: 1

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/metrics"
  prometheus.io/port: "8081"

imagePullSecrets: 
  - name: backend-docker-config-secret

nameOverride: ""
fullnameOverride: ""

image:
  repository: gitlab.praktikum-services.ru:5050/yuki.isoya23/momo-store/momo-backend
  pullPolicy: Always
  tag: "latest"

  containerPort: 8081

resources: 
  limits:
    cpu: "0.2"
    memory: 256Mi
  requests:
    cpu: "0.1"
    memory: 128Mi

service:
  type: ClusterIP
  port: 8081
  targetPort: 8081
  protocol: TCP

ingress:
  enabled: false