---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}-service
  labels:
    {{- include "frontend.labels" . | nindent 4}}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.image.containerPort }}
    protocol: {{ .Values.service.protocol }}
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4}}