apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8081"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: backend
    spec:
      imagePullSecrets:
        - name: docker-config-secret
      containers:
        - name: release-name-backend
          image: "gitlab.praktikum-services.ru:5050/yuki.isoya23/momo-store/momo-backend:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          resources:
            limits:
              cpu: "0.2"
              memory: 256Mi
            requests:
              cpu: "0.1"
              memory: 128Mi