---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-cfg
data:
  nginx.conf: |
    upstream backend {
      server backend:8081;
    }
    server {

      listen 80;
      server_name localhost;
      location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
      }

      location /products {
          proxy_pass http://backend;
      }

      location /categories {
          proxy_pass http://backend;
      }

      location /auth {
          proxy_pass http://backend;
      }
    }
